import { FONT } from './constants.js';

// ========================================
// STYLES - Premium, elegant, glassmorphism
// Theme-aware function
// ========================================
export default function getStyles(theme = 'dark') {
  const isDark = theme === 'dark';

  // Theme colors
  const colors = isDark ? {
    bgGradient: 'linear-gradient(145deg, #0f0c29 0%, #302b63 50%, #24243e 100%)',
    roomGradient: 'linear-gradient(160deg, #0f0c29 0%, #1a1040 30%, #302b63 60%, #24243e 100%)',
    textPrimary: '#fff',
    textSecondary: 'rgba(255,255,255,0.45)',
    textTertiary: 'rgba(255,255,255,0.35)',
    cardBg: 'rgba(255,255,255,0.06)',
    cardBorder: 'rgba(255,255,255,0.1)',
    inputBg: 'rgba(255,255,255,0.05)',
    inputBorder: 'rgba(255,255,255,0.08)',
    buttonOverlay: 'rgba(0,0,0,0.2)',
    headerBorder: 'rgba(255,255,255,0.05)',
    accentText: '#f5576c',
    accentGradient: 'linear-gradient(135deg, #f093fb 0%, #f5576c 50%, #4facfe 100%)',
    btnGradient: 'linear-gradient(135deg, #f5576c, #e94560)',
  } : {
    bgGradient: 'linear-gradient(145deg, #f5f5f5 0%, #ffffff 100%)',
    roomGradient: 'linear-gradient(145deg, #fafafa 0%, #ffffff 100%)',
    textPrimary: '#1a1a1a',
    textSecondary: 'rgba(0,0,0,0.6)',
    textTertiary: 'rgba(0,0,0,0.5)',
    cardBg: 'rgba(0,0,0,0.04)',
    cardBorder: 'rgba(0,0,0,0.08)',
    inputBg: 'rgba(0,0,0,0.05)',
    inputBorder: 'rgba(0,0,0,0.1)',
    buttonOverlay: 'rgba(255,255,255,0.8)',
    headerBorder: 'rgba(0,0,0,0.08)',
    accentText: '#f5576c',
    accentGradient: 'linear-gradient(135deg, #f093fb 0%, #f5576c 50%, #4facfe 100%)',
    btnGradient: 'linear-gradient(135deg, #f5576c, #e94560)',
  };

  const S = {
    page: { position:'fixed', top:0, left:0, right:0, bottom:0,
      background: colors.bgGradient,
      color: colors.textPrimary, fontFamily:FONT, overflow:'hidden' },
    center: { display:'flex', flexDirection:'column', alignItems:'center', justifyContent:'center',
      height:'100%', padding:'20px 16px', boxSizing:'border-box' },
    scrollCenter: { display:'flex', flexDirection:'column', alignItems:'center',
      height:'100%', padding:'20px 16px', boxSizing:'border-box',
      overflowY:'auto', WebkitOverflowScrolling:'touch' },
    title: { fontSize:26, fontWeight:700, letterSpacing:-0.5,
      background: colors.accentGradient,
      WebkitBackgroundClip:'text', WebkitTextFillColor:'transparent', marginBottom:4 },
    sub: { color: colors.textSecondary, fontSize:13, marginBottom:20, letterSpacing:0.3 },
    card: { width:'100%', maxWidth:380, background: colors.cardBg, borderRadius:24,
      padding:'22px 20px', backdropFilter:'blur(24px)', border:`1px solid ${colors.cardBorder}`,
      boxShadow: isDark ? '0 8px 32px rgba(0,0,0,0.4), inset 0 1px 0 rgba(255,255,255,0.06)' : '0 4px 16px rgba(0,0,0,0.08), inset 0 1px 0 rgba(255,255,255,0.8)' },
    cardTitle: { fontSize:15, fontWeight:600, textAlign:'center', marginBottom:16,
      color: isDark ? 'rgba(255,255,255,0.75)' : 'rgba(0,0,0,0.8)', letterSpacing:-0.2 },
    field: { marginBottom:14 },
    label: { fontSize:10, fontWeight:600, letterSpacing:1, color: colors.textTertiary, marginBottom:6,
      textTransform:'uppercase' },
    input: { width:'100%', padding:'12px 14px', borderRadius:14, background: colors.inputBg,
      border: `1px solid ${colors.inputBorder}`, color: colors.textPrimary, fontSize:15, outline:'none',
      boxSizing:'border-box', fontFamily:FONT, transition:'border-color 0.2s' },
    select: { width:'100%', padding:'12px 14px', borderRadius:14, background: colors.inputBg,
      border: `1px solid ${colors.inputBorder}`, color: colors.textPrimary, fontSize:15, outline:'none',
      boxSizing:'border-box', fontFamily:FONT },
    btn: { width:'100%', padding:'14px', borderRadius:16, border:'none',
      background: colors.btnGradient, color:'#fff', fontSize:15, fontWeight:600,
      cursor:'pointer', textAlign:'center', fontFamily:FONT, letterSpacing:-0.2,
      boxShadow:'0 6px 20px rgba(233,69,96,0.35)', transition:'transform 0.1s',
      WebkitTapHighlightColor:'transparent' },
    bigBtn: { width:'100%', maxWidth:380, display:'flex', alignItems:'center', gap:14, padding:'14px 16px',
      borderRadius:18, border:'none', color:'#fff', cursor:'pointer', marginBottom:10,
      background: colors.btnGradient, textAlign:'left',
      boxShadow:'0 6px 24px rgba(233,69,96,0.3)', fontFamily:FONT,
      WebkitTapHighlightColor:'transparent' },
    settingsBtn: { marginTop:16, padding:'10px 24px', borderRadius:14, background: colors.buttonOverlay,
      border: `1px solid ${colors.cardBorder}`, color: colors.textSecondary, fontSize:13,
      cursor:'pointer', fontFamily:FONT, WebkitTapHighlightColor:'transparent',
      backdropFilter:'blur(10px)' },
    avatarBtn: { width:52, height:52, borderRadius:16, border:'2px solid transparent',
      background:'none', fontSize:22, cursor:'pointer',
      display:'flex', alignItems:'center', justifyContent:'center', overflow:'hidden',
      WebkitTapHighlightColor:'transparent', transition:'all 0.15s', padding:0 },
    avatarSel: { borderColor:'#f5576c', background:'rgba(245,87,108,0.08)',
      boxShadow:'0 0 0 3px rgba(245,87,108,0.15)' },
    voiceBtn: { padding:'6px 14px', borderRadius:20, border: `1px solid ${colors.cardBorder}`,
      background: colors.buttonOverlay, color: colors.textSecondary, fontSize:12, cursor:'pointer',
      textTransform:'capitalize', fontFamily:FONT, WebkitTapHighlightColor:'transparent',
      transition:'all 0.15s' },
    voiceSel: { borderColor:'#f5576c', background:'rgba(245,87,108,0.12)', color: colors.textPrimary },
    toggle: { width:44, height:24, borderRadius:12, border:'none', padding:2, cursor:'pointer',
      display:'flex', alignItems:'center', transition:'background 0.2s',
      WebkitTapHighlightColor:'transparent' },
    toggleDot: { width:20, height:20, borderRadius:10, background: isDark ? '#fff' : '#1a1a1a', transition:'transform 0.2s' },
    topBar: { display:'flex', alignItems:'center', gap:12, width:'100%', maxWidth:380, marginBottom:16, flexShrink:0 },
    backBtn: { width:38, height:38, borderRadius:14, background: colors.buttonOverlay,
      border: `1px solid ${colors.cardBorder}`, color: colors.textPrimary, fontSize:18, cursor:'pointer',
      display:'flex', alignItems:'center', justifyContent:'center', fontFamily:FONT,
      WebkitTapHighlightColor:'transparent', backdropFilter:'blur(10px)' },
    shareBtn: { padding:'10px 24px', borderRadius:14, border: `1px solid ${colors.cardBorder}`,
      background: colors.buttonOverlay, color: colors.textSecondary, fontSize:13, cursor:'pointer',
      fontFamily:FONT, WebkitTapHighlightColor:'transparent', backdropFilter:'blur(10px)' },
    statusMsg: { marginTop:10, fontSize:12, color:'#f5576c', textAlign:'center' },
    // Mode buttons
    modeBtn: { flex:1, display:'flex', flexDirection:'column', alignItems:'center', gap:3,
      padding:'10px 4px', borderRadius:16, border: `1px solid ${colors.cardBorder}`,
      background: colors.buttonOverlay, color: colors.textSecondary, cursor:'pointer',
      WebkitTapHighlightColor:'transparent', transition:'all 0.2s', backdropFilter:'blur(8px)' },
    modeBtnSel: { borderColor:'rgba(245,87,108,0.35)', background:'rgba(245,87,108,0.1)', color: colors.textPrimary,
      boxShadow:'0 4px 16px rgba(245,87,108,0.15)' },
    // Room
    roomPage: { display:'flex', flexDirection:'column', position:'fixed', top:0, left:0, right:0, bottom:0,
      background: colors.roomGradient,
      color: colors.textPrimary, fontFamily:FONT },
    roomHeader: { display:'flex', alignItems:'center', padding:'8px 12px', gap:6,
      background: colors.buttonOverlay, borderBottom: `1px solid ${colors.headerBorder}`,
      flexShrink:0, backdropFilter:'blur(12px)' },
    backBtnSmall: { width:32, height:32, borderRadius:10, background:'transparent',
      border:'none', color: colors.textSecondary, fontSize:16, cursor:'pointer',
      display:'flex', alignItems:'center', justifyContent:'center', flexShrink:0,
      WebkitTapHighlightColor:'transparent' },
    iconBtn: { height:32, borderRadius:10, background: colors.buttonOverlay,
      border: `1px solid ${colors.cardBorder}`, color: colors.textPrimary, fontSize:14, cursor:'pointer',
      display:'flex', alignItems:'center', justifyContent:'center', flexShrink:0,
      WebkitTapHighlightColor:'transparent' },
    speakingBar: { display:'flex', alignItems:'center', gap:8, padding:'5px 14px',
      background:'rgba(245,87,108,0.06)', borderBottom:'1px solid rgba(245,87,108,0.1)',
      color:'#f5576c', fontSize:12, flexShrink:0 },
    speakingDots: { display:'flex', gap:3, alignItems:'center' },
    dot: { width:5, height:5, borderRadius:'50%', background:'#f5576c',
      animation:'vtPulse 1.2s infinite ease-in-out', display:'inline-block' },
    chatArea: { flex:1, overflowY:'auto', padding:'14px 12px', minHeight:0, WebkitOverflowScrolling:'touch' },
    bubble: { padding:'12px 16px', borderRadius:18, position:'relative',
      backdropFilter:'blur(16px)', border: `1px solid ${isDark ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.08)'}` },
    bubbleMine: { background:'rgba(245,87,108,0.1)', borderBottomRightRadius:6,
      boxShadow:'0 2px 12px rgba(245,87,108,0.08)' },
    bubbleOther: { background: isDark ? 'rgba(255,255,255,0.07)' : 'rgba(0,0,0,0.05)', borderBottomLeftRadius:6,
      boxShadow: isDark ? '0 2px 12px rgba(0,0,0,0.15)' : '0 2px 12px rgba(0,0,0,0.08)' },
    talkBar: { flexShrink:0, padding:'8px 16px 16px', display:'flex', flexDirection:'column', alignItems:'center',
      background:'transparent' },
    talkBtn: { display:'flex', alignItems:'center', justifyContent:'center',
      width:60, height:60, borderRadius:'50%', border:'none',
      background:'transparent', color: colors.textPrimary, fontSize:28, cursor:'pointer', touchAction:'manipulation',
      WebkitTapHighlightColor:'transparent', transition:'all 0.2s',
      filter:'drop-shadow(0 2px 8px rgba(0,0,0,0.3))' },
    talkBtnRec: { color:'#f5576c', fontSize:30,
      filter:'drop-shadow(0 0 12px rgba(245,87,108,0.4))' },
  };

  return S;
}
